Feature/object detection
Nova-UTD/navigator pull request #413
Opened 2024-02-21 21:06 UTC by Ayush-sharma-py

2024-04-09 19:44 UTC, danielv012 requested changes
Everything looks great, just need to trim a few things

2024-04-09 19:44 UTC, danielv012 commented on src/perception/object_detection_2D/test/test_pep257.py
What's this?

2024-04-09 19:44 UTC, danielv012 commented on src/perception/object_detection_2D/test/test_flake8.py
What's this?

2024-04-09 19:44 UTC, danielv012 commented on src/perception/object_detection_2D/test/test_copyright.py
What's this?

2024-04-09 19:44 UTC, danielv012 commented on my_package/test/test_pep257.py
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/test/test_flake8.py
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/test/test_copyright.py
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/setup.py
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/setup.cfg
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/resource/my_package
delete whole directory

2024-04-09 19:44 UTC, danielv012 commented on my_package/package.xml
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/my_package/my_node.py
delete

2024-04-09 19:44 UTC, danielv012 commented on my_package/my_package/__init__.py
delete

2024-04-09 19:44 UTC, danielv012 commented on launches/launch.vehicle.py
> +
unnecessary changes

2024-04-09 19:44 UTC, danielv012 commented on docker/entrypoint.sh
> +#export PYTHONPATH=$PYTHONPATH:"/models/research":"/models/research/slim"
remove

2024-04-09 19:44 UTC, danielv012 commented on Dockerfile
> +#FROM ubuntu:latest
can remove

2024-04-09 19:44 UTC, danielv012 commented on Dockerfile
> +#ADD src/perception/object_detection/cabc30fc-e7726578.mov models/research/object_detection/
Can remove

2024-04-09 19:44 UTC, danielv012 commented on Dockerfile
> +# TESTING
can remove

2024-04-22 17:35 UTC, closed without merging

2024-04-22 17:35 UTC, Ayush-sharma-py commented
Making a new Pull Request with the changes