Add Launch GUI (Zenith)
Nova-UTD/navigator pull request #415
Opened 2024-03-28 17:34 UTC by akevinge

In Draft due to lack of code docs.  

### Main Changes
- Add Zenith GUI + server

### Misc Changes
- Renamed docker container names to their respective service names (for some reason `navigator` and `navigator_obc` had the same, clashing container names).

2024-04-02 17:14 UTC, jruths commented
Sorry I missed the demo last week!  I'm looking forward to seeing this!  

Regarding the docker names... I guess it could be improper convention, but navigator was the name of the image and we had two services navigator_obc and navigator_carla.  This allows you to `docker compose build navigator` and build the image (once) for both `docker compose run navigator_obc` and `docker compose run navigator_carla`.  It seemed unnecessary to have two identical images named navigator_obc and navigator_carla.  Does that make sense?

2024-04-04 14:15 UTC, akevinge commented
> Sorry I missed the demo last week! I'm looking forward to seeing this!
> 
> Regarding the docker names... I guess it could be improper convention, but navigator was the name of the image and we had two services navigator_obc and navigator_carla. This allows you to `docker compose build navigator` and build the image (once) for both `docker compose run navigator_obc` and `docker compose run navigator_carla`. It seemed unnecessary to have two identical images named navigator_obc and navigator_carla. Does that make sense?

In theory, it shouldn't make a difference because it `navigator_obc` and `navigator_carla` all use the same `navigator` image. For example:
![image](https://github.com/Nova-UTD/navigator/assets/76929931/e67e0618-543c-4bb7-9066-e14c598fe116)

I could just be misunderstanding something though.

2024-04-09 20:36 UTC, danielv012 requested changes

2024-04-09 20:36 UTC, danielv012 commented on docker-compose.yml
> +      #runtime: nvidia
uncomment and outdent

2024-04-09 20:38 UTC, akevinge commented on docker-compose.yml
> +      #runtime: nvidia
Done

2024-04-09 20:38 UTC, danielv012 approved these changes

2024-04-09 20:49 UTC, merged