Keyboard controller
Nova-UTD/navigator pull request #435
Opened 2024-11-01 19:52 UTC by saishravanm

Completed rudimentary Keyboard Controller Node. Located in /src/tools/keyboard_controller. The code is simple enough that it can be tweaked easily, but in the future, hoping to use ROS parameters to set custom parameters for speed, throttle, etc. 

Controls: 
W - Throttle up 
S - Throttle down 
A - Go left 
D - Go right 
Hold X - Reverse
Hold X + W - Go backward

2024-11-05 02:53 UTC, jruths commented
Ah!  This needs to be a pull request into dev, not main!

2024-11-05 04:26 UTC, saishravanm commented
@jruths Fixed!

2024-11-08 14:48 UTC, akevinge requested changes

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/test/test_copyright.py
Let's delete this test if it's unused.

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/test/test_flake8.py
As previously commented.

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/test/test_pep257.py
Same for this.

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/keyboard_control/keyboard_control.py
> +            print("Going right!\n")
Do we need these print statements or are they just for debugging. If they're just for debugging, we should probably remove them.

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/keyboard_control/keyboard_control.py
> +    minimal_publisher = KeyboardController()
Nit: rename this to something that makes more sense.

2024-11-08 14:48 UTC, akevinge commented on src/tools/keyboard_control/keyboard_control/keyboard_control.py
> +        #print("Published Message!\n")
Debug statement left in here.

2024-11-12 03:19 UTC, akevinge approved these changes

2024-11-12 03:22 UTC, akevinge commented
Looks like the pre-compiled download URL for lemon is down. Feel free to merge despite the failing checks :+1:

2024-11-14 14:57 UTC, merged